// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Employee struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
	Role      string
}

type RefreshToken struct {
	Token      string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	EmployeeID uuid.UUID
	ExpiresAt  time.Time
}
